$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provision_start


date > /etc/vagrant_provision_end
echo I am provisioned.
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.82.68"
  config.vm.network "forwarded_port", guest: 8111, host: 8111
  config.vm.network "forwarded_port", guest: 5411, host: 5411

  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", inline: $script
  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/London /etc/localtime", run: "always"

  config.vm.provider "virtualbox" do |v|
    v.memory = 3096
    v.cpus = 4
  end
end
